# Generated by Django 5.1.1 on 2024-09-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custorem',
            new_name='customer',
        ),
    ]
