# Generated by Django 5.1.1 on 2024-09-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_custorem_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bio',
        ),
    ]
