"""
Django settings for book_store project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e00r!_nbkgowuszm-a=6w_@onpkd-m(wzan6_^6(zgt)qgyrd@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost']

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'paypal.standard.ipn',
    'store',
    'checkout'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'book_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.custorm_context_proccessor.website_store',
            ],
        },
    },
]

WSGI_APPLICATION = 'book_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

MEDIA_URL='/media/'
MEDIA_ROOT='media/'


STATIC_URL = '/static/'  # Ensure a trailing slash for proper URL handling

STATICFILES_DIRS = [
    BASE_DIR / "static",  # Static files directory at the project root
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # Directory for collected static files (using pathlib)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_HOST_USER = '1049c9898545e5'
EMAIL_HOST_PASSWORD = 'e8e952f325c879'
EMAIL_PORT = '2525'

SITE_URL = 'http://127.0.0.1:8000/'

STRIPE_PUBLISHABLE_KEY='pk_test_51Q106UDjCzAxwHyB4Bmmc02oOxef4EDex6KE15f22yquL4L4meYxVwOorzf8RQDAM0ivNPKLEWVYdD1P4LCmQZ0M00axZBQ2oN'
STRIPE_SECRET_KEY='sk_test_51Q106UDjCzAxwHyBxxQxxY9etR4EeTAxaDTUdI72wN3FWgS797rcf4pQ1SrLMkhOBQ51XBvLDjKPPRSHOL9g4tnv00qtThAk9d'
STRIPE_ENDPOINT_SECRET = 'whsec_0f3eb6d87e8ea5bdc321eb2b9330150510f0b97e5263d2199a8275406e648c8e'

PAYPAL_TEST = True
PAYPAL_EMAIL = 'sb-ixvs334049410@business.example.com'
CURRENCY='USD'
